### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by steveuk23** [re-1st/HA-3d-floorplan#1]
Looks great mate. 
Seen you link it on a home assistant group.
I like the idea of having the panel embedded into your background image. 
Can I ask what 'panel_custom' is in your configuration.yaml ?
I've got nearly everything else you have but never seen that lol. 
Oh also can I ask how much you created within SketchUp ? Was it just the house structure or did you add the furniture with them as well, as I've struggled when I've used SketchUp especially trying to find matching furniture as I have some IKEA furniture and the libraries I've tried don't have much.
Thanks

**Comment by re-1st** [comment]
thanks mate! 
panel_custom in the config.yaml is actually totally unrelated to the floorplan :) 
this feature can bring custom shortcuts into the left sidebar. But thanks for pointing it out because I now realize that this could be the reason the order of shortcuts in the sidepanel is messed up everytime I reboot 😅

long story short:  i will remove this from my config :)

**Comment by steveuk23** [comment]
Ah yeah just looked it up see what you mean now looks like it could be handy I suppose.
If you get a minute could you tell briefly tell me how much of the process you do within SketchUp.
Thanks

**Comment by re-1st** [comment]
To answer that question short: i did spend lots of hours in Sketchup. Mainly because at fist, i tried to build everything myself.  Just try to find existing models from the community (3d warehouse). For the renderings you have to find the right settings for everything to work correctly (that took me a while) but i will try to make a video on this subject soon.
